//@version=5
//@author=Ricardo Montserrat
strategy('Rich Bot', shorttitle='RtBot', precision=2, overlay=true, initial_capital=1000, commission_type=strategy.commission.percent, commission_value=0.1, currency='USD', calc_on_every_tick=true)

print(string txt) => 
	var table t = table.new(position.middle_right, 1, 1)
	table.cell(t, 0, 0, txt, bgcolor = color.yellow)

visuals = 'Visuals'

// --- UT BOT ---

UTBOT_TAG = 'UT Bot'

KEY_VALUE = input(2, title='Key Vaule. \'This changes the sensitivity\'', group=UTBOT_TAG)
ATR_PERIOD = input(1, title='ATR Period', group=UTBOT_TAG)

SHOW_BARCOLOR = input(false, title='Show Bar Color', group=visuals)
SHOW_UTSIGNAL = input(false, title='Show UT Signal', group=visuals)

// Average true range (ATR), high == high volatility, low == low volatility
// Uses Moving Average of price to calculate volatility
LOSS_TOLERATE_AMOUNT = KEY_VALUE * ta.atr(ATR_PERIOD)

trailingStopATRs = array.new_float(size = 3, initial_value = .0) 
utbot(timeframe, idx) =>
    [tfClose] = request.security(syminfo.tickerid, timeframe, [close])

    trailingStopATR = array.get(trailingStopATRs, idx) 
    lastTrail = nz(trailingStopATR[1], .0)

    closeHigh = close > lastTrail
    lastCloseHigh = close[1] > lastTrail

    higherClose = closeHigh ? close - LOSS_TOLERATE_AMOUNT : close + LOSS_TOLERATE_AMOUNT
    lowerClose = not (closeHigh or lastCloseHigh) ? math.min(lastTrail, close + LOSS_TOLERATE_AMOUNT) : higherClose
    trailingStopATR := closeHigh and lastCloseHigh ? math.max(lastTrail, close - LOSS_TOLERATE_AMOUNT) : lowerClose

    ema = ta.ema(close, 1)
    above = ta.crossover(ema, trailingStopATR)
    below = ta.crossover(trailingStopATR, ema)

    uptrend = close > trailingStopATR

    [uptrend ? color.green : color.red, uptrend and above, not uptrend and below]

[utbotColor1, utbotBuy1, utbotSell1] = utbot('1', 0)
[utbotColor3, utbotBuy3, utbotSell3] = utbot('3', 1)
[utbotColor5, utbotBuy5, utbotSell5] = utbot('5', 2)

plotshape(SHOW_UTSIGNAL and utbotBuy3, title='Buy', text='Buy', style=shape.labelup, location=location.belowbar, color=color.new(color.green, 0), textcolor=color.white, size=size.tiny)
plotshape(SHOW_UTSIGNAL and utbotSell3, title='Sell', text='Sell', style=shape.labeldown, location=location.abovebar, color=color.new(color.red, 0), textcolor=color.white, size=size.tiny)

barcolor(SHOW_BARCOLOR ? utbotColor3 : na)

// --- Box Bot ---

BOXBOT_TAG = 'Box Bot'

var color TRANSPARENT = color.new(color.white, 100)

FAST_PERIOD_K = input.int(title='Fast Period', minval=1, defval=24, group=BOXBOT_TAG)
SLOW_PERIOD_D = input.int(title='Slow Period', minval=1, defval=3, group=BOXBOT_TAG)
SMOOTH_FAST_PERIOD = input.int(title='Smooth', minval=1, defval=5, group=BOXBOT_TAG)

OVERBOUGHT_LEVEL = input(title='Overbought Level', defval=70, group=BOXBOT_TAG)
OVERSOLD_LEVEL = input(title='Oversold Level', defval=20, group=BOXBOT_TAG)

SHOW_STOCHASTIC = input(false, title='Show Stochastic', group=visuals)

boxbot(timeframe) =>
    [tfClose, tfHigh, tfLow] = request.security(syminfo.tickerid, timeframe, [close, high, low])

    fastPeriod = ta.sma(ta.stoch(tfClose, tfHigh, tfLow, FAST_PERIOD_K), SMOOTH_FAST_PERIOD)
    slowPeriod = ta.sma(fastPeriod, SLOW_PERIOD_D)

    [fastPeriod, slowPeriod, fastPeriod > OVERBOUGHT_LEVEL, fastPeriod < OVERSOLD_LEVEL]

[fastPeriod1, slowPeriod1, overbought1, oversold1] = boxbot('1')
[fastPeriod3, slowPeriod3, overbought3, oversold3] = boxbot('3')
[fastPeriod5, slowPeriod5, overbought5, oversold5] = boxbot('5')

getvalue(value) => SHOW_STOCHASTIC ? value : na

trendColor = fastPeriod3 > slowPeriod3 ? color.green : color.red
plot(getvalue(fastPeriod3), title='%Fast', color=trendColor)
plot(getvalue(slowPeriod3), title='%Slow', color=trendColor)

overboughtColor = overbought3 ? color.red : na
oversoldColor = oversold3 ? color.green : na

hline(getvalue(50), title='Middle Band', color=color.new(color.white, 50))
fill(hline(getvalue(100), color=TRANSPARENT), hline(getvalue(OVERBOUGHT_LEVEL), color=color.red), title='Upper Band Breakout', color=color.new(overboughtColor, 50))
fill(hline(getvalue(0), color=TRANSPARENT), hline(getvalue(OVERSOLD_LEVEL), color=color.green), title='Lower Band Breakout', color=color.new(oversoldColor, 50))

plotshape(SHOW_STOCHASTIC and ta.crossover(fastPeriod3, slowPeriod3) ? fastPeriod3 : na, title='Fast/Slow Crossover', location=location.absolute, style=shape.circle, size=size.tiny, color=color.green)
plotshape(SHOW_STOCHASTIC and ta.crossunder(fastPeriod3, slowPeriod3) ? slowPeriod3 : na, title='Fast/Slow Crossunder', location=location.absolute, style=shape.circle, size=size.tiny, color=color.red)

// --- SMI Bot ---

SMIBOT_TAG = 'SMI Bot'

LOOKBACK_PERIOD = input.int(title='Stochastic Lookback', defval=13, minval=1, group=SMIBOT_TAG)
SMOOTH_LEN1 = input.int(title='1st Smoothing Length', defval=25, minval=1, group=SMIBOT_TAG)
SMOOTH_LEN2 = input.int(title='2nd Smoothing Length', defval=2, minval=1, group=SMIBOT_TAG)
SIGNAL_LENGTH = input.int(title='Signal Length', defval=12, minval=1, group=SMIBOT_TAG)

SHOW_SMI = input(false, title='Show SMI', group=visuals)

smibot(timeframe) =>
    [tfClose] = request.security(syminfo.tickerid, timeframe, [close])

    highestHigh = ta.highest(LOOKBACK_PERIOD)
    lowestLow = ta.lowest(LOOKBACK_PERIOD)

    numerator = ta.ema(ta.ema(tfClose - 0.5 * (highestHigh + lowestLow), SMOOTH_LEN1), SMOOTH_LEN2)
    denominator = 0.5 * ta.ema(ta.ema(highestHigh - lowestLow, SMOOTH_LEN1), SMOOTH_LEN2)

    smi = 100 * numerator / denominator
    signal = ta.ema(smi, SIGNAL_LENGTH)

    [smi, signal, smi > signal]

[smi1, signal1, uptrend1] = smibot('1')
[smi3, signal3, uptrend3] = smibot('3')
[smi5, signal5, uptrend5] = smibot('5')

trendColor := uptrend3 ? color.yellow : color.blue

getvalueSMI(value) => SHOW_SMI ? value : na

plot(getvalueSMI(smi3), title='SMI', color=trendColor)
plot(getvalueSMI(signal3), title='Signal', color=trendColor)

plotshape(SHOW_SMI and ta.crossover(smi3, signal3) ? smi3 : na, title='Crossover', location=location.absolute, style=shape.circle, size=size.tiny, color=color.green)
plotshape(SHOW_SMI and ta.crossunder(smi3, signal3) ? smi3 : na, title='Crossunder', location=location.absolute, style=shape.circle, size=size.tiny, color=color.red)

// --- RT BOT ---

RTBOT_TAG = 'RT Bot'

BOX_CLOSENESS = input.int(title='Box Close Length', minval=1, defval=3, group=RTBOT_TAG)
UTSIGNAL_CLOSENESS = input.int(title='UT Signal Close Length', minval=1, defval=3, group=RTBOT_TAG)
BOX_5MIN_CLOSENESS = input.int(title='Box 5min Length', minval=1, defval=8, group=RTBOT_TAG)

isclose(condition, length) =>
    for i = 0 to length
        if condition[i]
            true

overbought = isclose(overbought3, BOX_CLOSENESS) and isclose(overbought1, BOX_CLOSENESS)
oversold = isclose(oversold3, BOX_CLOSENESS) and isclose(oversold1, BOX_CLOSENESS)

utBuy = isclose(utbotBuy3, UTSIGNAL_CLOSENESS) and isclose(utbotBuy1, UTSIGNAL_CLOSENESS)
utSell = isclose(utbotSell3, UTSIGNAL_CLOSENESS) and isclose(utbotSell1, UTSIGNAL_CLOSENESS)

call = utBuy and oversold and uptrend3
put = utSell and overbought and not uptrend3

if call
    strategy.entry('Call', strategy.long)
else if put
    strategy.entry('Put', strategy.short)

isOversold5 = isclose(oversold5, BOX_5MIN_CLOSENESS)
isOverbought5 = isclose(overbought5, BOX_5MIN_CLOSENESS)

closePut = utbotBuy5 and isOversold5 or call
closeCall = utbotSell5 and isOverbought5 or put

if closePut
    strategy.close('Put')
else if closeCall
    strategy.close('Call')

plotshape(closePut, location=location.belowbar, style=shape.triangleup, size=size.normal, color=color.purple)
plotshape(closeCall, location=location.abovebar, style=shape.triangledown, size=size.normal, color=color.purple)

plotshape(call, location=location.belowbar, style=shape.triangleup, size=size.huge, color=color.green)
plotshape(put, location=location.abovebar, style=shape.triangledown, size=size.huge, color=color.red)
