//@version=5
indicator('Stochastic V5', shorttitle='StochV5', precision=2)

var color TRANSPARENT = color.new(color.white, 100)

FAST_PERIOD_K = input.int(title='Fast Period', minval=1, defval=24)
SLOW_PERIOD_D = input.int(title='Slow Period', minval=1, defval=3)

SMOOTH_FAST_PERIOD = input.int(title='Smooth', minval=1, defval=5)
OVERBOUGHT_LEVEL = input(title='Overbought Level', defval=70)
OVERSOLD_LEVEL = input(title='Oversold Level', defval=20)

MAX_LEVEL = input(title='Max Level', defval=100)
MIN_LEVEL = input(title='Min Level', defval=0)

fastPeriod = ta.sma(ta.stoch(close, high, low, FAST_PERIOD_K), SMOOTH_FAST_PERIOD)
slowPeriod = ta.sma(fastPeriod, SLOW_PERIOD_D)

trendColor = fastPeriod > slowPeriod ? #0ebb23 : color.red
plot(fastPeriod, title='%Fast', color=trendColor)
plot(slowPeriod, title='%Slow', color=trendColor)

overboughtColor = fastPeriod > OVERBOUGHT_LEVEL ? color.red : na
oversoldColor = fastPeriod < OVERSOLD_LEVEL ? color.green : na

hline(50, title='Middle Level', color=color.new(color.white, 50))
fill(hline(100, color=TRANSPARENT), hline(OVERBOUGHT_LEVEL, color=color.red), title='Upper Band Breakout', color=color.new(overboughtColor, 50))
fill(hline(0, color=TRANSPARENT), hline(OVERSOLD_LEVEL, color=color.green), title='Lower Band Breakout', color=color.new(oversoldColor, 50))

plotshape(ta.crossover(fastPeriod, slowPeriod) ? fastPeriod : na, title='Fast/Slow Crossover', location=location.absolute, style=shape.circle, size=size.tiny, color=color.green)
plotshape(ta.crossunder(fastPeriod, slowPeriod) ? slowPeriod : na, title='Fast/Slow Crossunder', location=location.absolute, style=shape.circle, size=size.tiny, color=color.red)