//@version=5
indicator(title='UT Bot V5', shorttitle='UTBv5', overlay=true)

KEY_VALUE = input(2, title='Key Vaule. \'This changes the sensitivity\'')
ATR_PERIOD = input(1, title='ATR Period')
SRC = close

nLoss = KEY_VALUE * ta.atr(ATR_PERIOD)

trailingStopATR = 0.0
iff_1 = SRC > nz(trailingStopATR[1], 0) ? SRC - nLoss : SRC + nLoss
iff_2 = SRC < nz(trailingStopATR[1], 0) and SRC[1] < nz(trailingStopATR[1], 0) ? math.min(nz(trailingStopATR[1]), SRC + nLoss) : iff_1
trailingStopATR := SRC > nz(trailingStopATR[1], 0) and SRC[1] > nz(trailingStopATR[1], 0) ? math.max(nz(trailingStopATR[1]), SRC - nLoss) : iff_2

pos = 0
iff_3 = SRC[1] > nz(trailingStopATR[1], 0) and SRC < nz(trailingStopATR[1], 0) ? -1 : nz(pos[1], 0)
pos := SRC[1] < nz(trailingStopATR[1], 0) and SRC > nz(trailingStopATR[1], 0) ? 1 : iff_3

xcolor = pos == -1 ? color.red : pos == 1 ? color.green : color.blue

ema = ta.ema(SRC, 1)
above = ta.crossover(ema, trailingStopATR)
below = ta.crossover(trailingStopATR, ema)

buy = SRC > trailingStopATR and above
sell = SRC < trailingStopATR and below

barbuy = SRC > trailingStopATR
barsell = SRC < trailingStopATR

plotshape(buy, title='Buy', text='Buy', style=shape.labelup, location=location.belowbar, color=color.new(color.green, 0), textcolor=color.new(color.white, 0), size=size.tiny)
plotshape(sell, title='Sell', text='Sell', style=shape.labeldown, location=location.abovebar, color=color.new(color.red, 0), textcolor=color.new(color.white, 0), size=size.tiny)

barcolor(barbuy ? color.green : na)
barcolor(barsell ? color.red : na)